target-version = "py39"
line-length = 120
format.quote-style = "single"

[lint]
select = ["ALL"]
ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D100",   # Missing docstring in public module
    "D104",   # Missing docstring in public package
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the first line
    "PD901",  # Avoid using the generic variable name df for DataFrames
    "Q000",   # Single quotes found but double quotes preferred
    "S101",   # Use of `assert` detected
    "SLF001", # Private member accessed
    "TRY300", # Consider moving this statement to an else block
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    ".env",
    ".venv",
    "venv",
]
